M48
; DRILL file {KiCad 9.0.4} date 2025-08-19T16:45:50+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-19T16:45:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X139.593Y-33.69
T2
X87.5Y-28.5
X87.5Y-60.0
X145.5Y-28.5
X145.5Y-60.0
M30
